# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/*.Functions.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- powershell: |
    $websiteDirectory = "$(Build.SourcesDirectory)\src\Rates.Web\wwwroot"
    Copy-Item "$websiteDirectory\settings.prod.js" "$websiteDirectory\settings.js" -Force
  displayName: 'Update javascript settings'

- task: CopyFiles@2
  displayName: 'Copy website files to artifacts'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/src/Rates.Web/wwwroot'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/site'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
