# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release

steps:
  - task: DotNetCoreCLI@2
    displayName: "dotnet publish"
    inputs:
      command: publish
      publishWebProjects: False
      projects: "**/*.Functions.csproj"
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: True

  - task: AzureFunctionApp@1
    displayName: 'Azure Function App Deploy: ratesfenton'
    inputs:
      azureSubscription: 'Visual Studio Professional with MSDN (fbcfa0cd-2f10-4cda-9539-f4ad99c3d654)'
      appType: functionApp
      appName: ratesfenton

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
      artifactName: "drop"
