# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: windows-latest

variables:
  buildConfiguration: Release

steps:
  - task: DotNetCoreCLI@2
    displayName: "dotnet publish"
    inputs:
      command: publish
      publishWebProjects: False
      projects: "**/*.Functions.csproj"
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
      zipAfterPublish: True

  - task: AzureFunctionApp@1
    displayName: 'Azure Function App Deploy: ratesfenton'
    inputs:
      azureSubscription: 'Pay-As-You-Go(42df69a9-0c66-4d1b-ac12-36367bd20375)'
      appType: 'functionApp'
      appName: 'ratesfenton'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
      deploymentMethod: 'auto'
