# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016'

steps:
- powershell: .\Build.ps1 -version $(Build.BuildId)
  displayName: Build.ps1

- task: PublishBuildArtifacts@1
  displayName: Publish Rates.Web
  inputs:
     pathtoPublish: '$(Agent.BuildDirectory)\publish\Rates.Web' 
     artifactName: 'Rates.Web' 

- task: PublishBuildArtifacts@1
  displayName: Publish Rates.Fetcher
  inputs:
     pathtoPublish: '$(Agent.BuildDirectory)\src\Rates.Fetcher\bin\Release\net461' 
     artifactName: 'Rates.Fetcher' 